const data = {
    products: [
      {
        name: 'Fettuccine Alfredo',
        slug: 'fettuccine Alfredo',
        category: 'mill',
        image: '/images/p1.jpg', // 679px × 829px
        price: 120,
        countInStock: 10,
        brand: 'food',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality shirt',
      },
      {
        name: 'Skillet Apple Pork Chops',
        slug: 'skillet Apple Pork Chops',
        category: 'firstfood',
        image: '/images/p2.jpg',
        price: 250,
        countInStock: 20,
        brand: 'Foodi',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        name: 'Fresh sardines',
        slug: 'fresh sardines',
        category: 'lunch',
        image: '/images/p3.jpg',
        price: 25,
        countInStock: 15,
        brand: 'Foods',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        name: 'Chivito uruguayo',
        slug: 'chivito uruguayo',
        category: 'Brackfirst',
        image: '/images/p4.jpg',
        price: 65,
        countInStock: 5,
        brand: 'Pood',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
    ],
  };
  export default data;